version: "3"

# This docker-compose is for developer convenience, not for running in production.

networks:
  # The kbase-dev custom network is used by kbase-ui and friends. Using this network allows
  # the kbase-ui proxier to keep services requests local, or forward to kbase; it also allows
  # the search services kafa, zookeeper, and elasticsearch to talk to each other at known hostnames.
  kbase-dev:
    external: true

services:
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka
    networks: [kbase-dev]
    ports:
      - "127.0.0.1:9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx512m -Xms512m

  # Required for kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: [kbase-dev]
    ports:
      - "127.0.0.1:2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:12888:13888
